

-- use sql_journey database
use sql_journey

-- Write a SQL query to retrieve the total number of orders for each customer from the "orders" table.
select c.name as customer, count(o.order_id) as Total_orders 
from orders o 
join customers c on o.customer_id = c.customer_id 
group by customer;

-- Write a SQL query to retrieve the average price of products in each category from the "products" table.
select category, avg(price) as Average_price
from product
group by category;

-- Write a SQL query to retrieve the maximum salary for each department from the "employees" table.
select department, max(salary) as maximum_salary 
from employees
group by department;

-- Write a SQL query to retrieve the total revenue generated by each customer from the "orders", "order_items" and "product" tables.
select o.customer_id as customer_id, sum(oi.quantity * p.price) as total_revenue
from orders o 
join order_item oi on o.order_id = oi.order_id 
join product p on p.product_id = oi.product_id 
group by o.customer_id;

